site_name: fiware TRUE Connector
site_url: https://true-connector.readthedocs.org
repo_url: https://github.com/Engineering-Research-and-Development/fiware-true-connector
site_description: TRUE Connector Documentation
docs_dir: docs
site_dir: html
markdown_extensions: [toc, fenced_code]
use_directory_urls: false
theme: readthedocs
extra_css:
  [
    "https://www.fiware.org/style/fiware_readthedocs.css",
    "https://www.fiware.org/style/fiware_readthedocs_iot.css",
  ]
google_analytics: ["UA-118589264-1", "true-connector.readthedocs.io"]
pages:
  - "Home - Getting Started": "index.md"
  - "Quick Start Guide": "quick_start_guide.md"
  - "Create new docker image": "docker_readme.md"
  - "User & Programmers Manual": "user_and_programmers_manual.md"
  - "Tutorial": "true_connector_tutorial.md"